apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  forward.server: |
    alaskaair.com:53 {
        forward alaskaair.com 10.13.3.240
    }
    bc.alaskasworld.com:53 {
        forward bc.alaskasworld.com 1.1.1.1
    }
    insideaag.com:53 {
        forward insideaag.com 10.13.3.240
    }
